In [1]:
import tensorflow as tf

In [5]:
variavel = tf.Variable(2)


In [10]:
init = tf.compat.v1.global_variables_initializer()

#with tf.compat.v1.Session() as sess:
    
#    sess.run(init)
#    rodar = sess.run(variavel)
#    sess.close()
#print(rodar)
tf.print(variavel)

2


In [13]:
matriz = tf.compat.v1.random_normal((3,5),0,1) #(shape, média, desvio padrão)


In [14]:
variavel2 = tf.Variable(matriz)

In [16]:
init = tf.compat.v1.global_variables_initializer()
tf.print(variavel2)
#with tf.compat.v1.Session() as sess:
#    sess.run(init)
#    rodar = sess.run(variavel2)
#print(rodar)

[[-0.643605888 -0.0856599063 0.0947025 -0.575958788 -0.686628]
 [1.62094367 -0.512784362 -0.716008306 -2.22497201 1.20326459]
 [0.0545677803 -1.14402533 0.0114231985 -0.712532222 0.678216815]]
